dist: xenial
language: python
branches:
  only:
  - master

jobs:
 include:
   - python: 3.8
     env: TOXENV=travis
     install: pip install tox
     script: tox -e $TOXENV
     after_script: rm -rf ./.tox

notifications:
  email:
    recipients:
    - dev@gridsingularity.com